### PR TITLE
add files to gitignore

### PR DESCRIPTION
**Pull request by tatterdemalion**
There was no `.gitignore` file. I created a basic one from a template. 
The template already had records for `__pycache__` directories. 

I added:

* db.sqlite3
* media/*

### CODE REVIEW

**Comment by tatterdemalion** [comment]
@bahattincinic 
I did not see that. What is this directory supposed to be anyway?

**Comment by bahattincinic** [comment]
@tatterdemalion https://github.com/kaaanshady/guitar-project-django/tree/master/.idea

**Comment by tatterdemalion** [comment]
@bahattincinic Sorry. I should have been more clear. What is the purpose of it? Is it there because of pycharm or something?

**Comment by bahattincinic** [comment]
I'm not sure about PyCharm. I remembered https://github.com/django/django/pull/5091 Pull request.  

```
I believe there are two reasonable courses of action here:

Keep Python/Django-specific ignores only and tell people to add whatever they need for their development tools by setting core.excludesFile in their ~/.gitconfig (as recommended on http://git-scm.com/docs/gitignore).

Add ignores for all common development tools. In that case I would suggest to take GitHub's default .gitignore for Python projets and extend it with Django's current .gitignore.
Option 2 is better than fixing the problem piecewise every time a user complains ;-)
```

😄

**Pull request merged**
